version: '3'
services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo-user:mongo-pass@mongo:27017/link-shortener?authSource=admin
    command: npm run start:dev
